emit:
  - '@typespec/openapi3'
  - "@azure-tools/typespec-ts"
options:
  "@azure-tools/typespec-ts":
    title: GreenbeltSDK
    generateMetadata: true
    generateTest: true
    "emitter-output-dir": "{output-dir}"
    packageDetails:
      name: "@azure-rest/xbox-greenbelt"
      description: "Greenbelt Client"
      version: "1.0.0-beta.1"
